"""add is_public to Complaint

Revision ID: 5e91b75f693a
Revises: 679164407868
Create Date: 2025-05-11 13:44:56.756272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e91b75f693a'
down_revision: Union[str, None] = '679164407868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_uid'), 'user', ['user_uid'], unique=True)
    op.add_column('complaint', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'complaint', 'user', ['user_uid'], ['user_uid'])
    op.drop_column('complaint', 'tone')
    op.add_column('reply', sa.Column('user_uid', sa.String(), nullable=True))
    op.create_index(op.f('ix_reply_user_uid'), 'reply', ['user_uid'], unique=False)
    op.create_foreign_key(None, 'reply', 'user', ['user_uid'], ['user_uid'])
    op.create_foreign_key(None, 'user_info', 'user', ['user_uid'], ['user_uid'])
    op.create_foreign_key(None, 'user_reply_history', 'user', ['user_uid'], ['user_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reply_history', type_='foreignkey')
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_index(op.f('ix_reply_user_uid'), table_name='reply')
    op.drop_column('reply', 'user_uid')
    op.add_column('complaint', sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.drop_column('complaint', 'is_public')
    op.drop_index(op.f('ix_user_user_uid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
