"""rename password to password

Revision ID: 79ea942ef5fc
Revises: 9b4493d0f0b0
Create Date: 2025-04-20 19:55:58.726894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ea942ef5fc'
down_revision: Union[str, None] = '9b4493d0f0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'complaint', 'user', ['user_uid'], ['user_uid'])
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user_info', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    # ### end Alembic commands ###
