"""remove tone column

Revision ID: 9b4493d0f0b0
Revises: fee5251d6160
Create Date: 2025-04-19 20:13:30.499081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4493d0f0b0'
down_revision: Union[str, None] = 'fee5251d6160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('user_uid', sa.String(), nullable=True))
    op.drop_index('ix_complaint_user_id', table_name='complaint')
    op.create_index(op.f('ix_complaint_user_uid'), 'complaint', ['user_uid'], unique=False)
    op.drop_constraint('complaint_user_id_fkey', 'complaint', type_='foreignkey')
    #op.create_foreign_key(None, 'complaint', 'user', ['user_uid'], ['user_uid'])
    op.drop_column('complaint', 'user_id')
    op.drop_column('reply', 'tone')
    op.add_column('user', sa.Column('user_uid', sa.String(), nullable=True))
    op.add_column('user', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_user_uid'), 'user', ['user_uid'], unique=True)
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.drop_column('user', 'username')
    op.add_column('user_info', sa.Column('user_uid', sa.String(), nullable=True))
    op.drop_index('ix_user_info_user_id', table_name='user_info')
    op.create_index(op.f('ix_user_info_user_uid'), 'user_info', ['user_uid'], unique=True)
    op.create_foreign_key(None, 'user_info', 'user', ['user_uid'], ['user_uid'])
    op.drop_column('user_info', 'user_id')
    op.add_column('user_reply_history', sa.Column('user_uid', sa.String(), nullable=True))
    op.drop_index('ix_user_reply_history_user_id', table_name='user_reply_history')
    op.create_index(op.f('ix_user_reply_history_user_uid'), 'user_reply_history', ['user_uid'], unique=False)
    op.drop_constraint('user_reply_history_user_id_fkey', 'user_reply_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_reply_history', 'user', ['user_uid'], ['user_uid'])
    op.drop_column('user_reply_history', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reply_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_reply_history', type_='foreignkey')
    op.create_foreign_key('user_reply_history_user_id_fkey', 'user_reply_history', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_reply_history_user_uid'), table_name='user_reply_history')
    op.create_index('ix_user_reply_history_user_id', 'user_reply_history', ['user_id'], unique=False)
    op.drop_column('user_reply_history', 'user_uid')
    op.add_column('user_info', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_index(op.f('ix_user_info_user_uid'), table_name='user_info')
    op.create_index('ix_user_info_user_id', 'user_info', ['user_id'], unique=False)
    op.drop_column('user_info', 'user_uid')
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_user_uid'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'user_uid')
    op.add_column('reply', sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('complaint', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.create_foreign_key('complaint_user_id_fkey', 'complaint', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_complaint_user_uid'), table_name='complaint')
    op.create_index('ix_complaint_user_id', 'complaint', ['user_id'], unique=False)
    op.drop_column('complaint', 'user_uid')
    # ### end Alembic commands ###
